# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'TwitterTweets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterTweets
    pod 'Kingfisher'
    pod 'OAuthSwift', '~> 1.2.0'
    pod 'SwiftyJSON', '~> 4.0'

  target 'TwitterTweetsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterTweetsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
